### ISSUE TITLE
Open a project Slack workspace

### ISSUE THREAD

**Issue by moshewe** [luc-tielen/eclair-lang#138]
I think opening a Slack for Eclair will improve communication and encourage people to get involved with the project.

**Comment by luc-tielen** [comment]
Hi, thanks for asking this!

I've actually been working on this already, the past month or so I've been working on the [website for Eclair](https://eclair-lang.org), but I haven't publicly announced it yet. (I still have some things to fix like navigation on mobile, and add more pages.)

On the website I also added a Discord link, but again not announced yet so there's only a few people in there for now. Feel free to join though! And let me know what you think of the website. :smiley:

The next month I will be really busy with work but after that I will have more time for Eclair again so hopefully I can finish the last few things on the website then.

Btw, I chose Discord over Slack because Slack has a limited history of messages for free communities, which I found very frustrating in the past..

Closing this issue since it's already handled, hope to see you in the Discord.
